name: volleyball_training

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  formz: ^0.6.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  easy_localization: ^3.0.3
  modal_bottom_sheet: ^3.0.0
  equatable: ^2.0.5
  keyboard_dismisser: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  dart_style: ^2.3.6

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lotties/
    - assets/translations/
    - assets/gifs/
    - assets/gifs/jump/
    - assets/gifs/rubber_hand/


